package clonedata

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// ParseTableList parses `SHOW TABLES`-style -N output (one table name per
// line, no header) into a slice, skipping blank lines.
func ParseTableList(out string) []string {
	var tables []string
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			tables = append(tables, line)
		}
	}
	return tables
}

// ParseCount parses a single `SELECT COUNT(*)`-style -N output (one integer
// on one line) into an int64.
func ParseCount(out string) (int64, error) {
	trimmed := strings.TrimSpace(out)
	n, err := strconv.ParseInt(trimmed, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("clonedata: parse row count %q: %w", trimmed, err)
	}
	return n, nil
}

// RowCountDiff compares two table->count maps (source vs target,
// immediately post-restore, per DESIGN.md §9's acceptance criterion) and
// returns a sorted, human-readable list of mismatches — a table present on
// only one side, or present on both with different counts. An empty slice
// means every table generated by the SHOW TABLES-driven enumeration matched
// exactly (WP3-data-leg.md §4 I-F: the list is generated dynamically, never
// a hand-picked subset, so a table added next month is covered
// automatically).
func RowCountDiff(source, target map[string]int64) []string {
	seen := make(map[string]bool, len(source))
	var mismatches []string
	for name, sc := range source {
		seen[name] = true
		tc, ok := target[name]
		switch {
		case !ok:
			mismatches = append(mismatches, fmt.Sprintf("%s: source has %d rows, target table missing", name, sc))
		case sc != tc:
			mismatches = append(mismatches, fmt.Sprintf("%s: source has %d rows, target has %d", name, sc, tc))
		}
	}
	for name, tc := range target {
		if !seen[name] {
			mismatches = append(mismatches, fmt.Sprintf("%s: target has %d rows, source table missing", name, tc))
		}
	}
	sort.Strings(mismatches)
	return mismatches
}
